src/web/DevStore.WebApp.MVC/Controllers/CatalogController.cs
using DevStore.WebApp.MVC.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace DevStore.WebApp.MVC.Controllers
{
    public class CatalogController : MainController
    {
        private readonly ICatalogService _catalogService;

        public CatalogController(ICatalogService catalogService)
        {
            _catalogService = catalogService;
        }

        [HttpGet]
        [Route("")]
        [Route("showcase")]
        public async Task<IActionResult> Index([FromQuery] int ps = 8, [FromQuery] int page = 1, [FromQuery] string q = null)
        {
            var products = await _catalogService.ListAll(ps, page, q);
            ViewBag.Search = q;
            products.ReferenceAction = "Index";

            return View(products);
        }

        [HttpGet]
        [Route("products/{id}")]
        public async Task<IActionResult> ProductDetails(Guid id)
        {
            var product = await _catalogService.GetById(id);

            return View(product);
        }
    }
}

src/web/DevStore.WebApp.MVC/Controllers/ShoppingCartController.cs
using DevStore.WebApp.MVC.Models;
using DevStore.WebApp.MVC.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace DevStore.WebApp.MVC.Controllers
{
    [Authorize, Route("shopping-cart")]
    public class ShoppingCartController : MainController
    {
        private readonly ICheckoutBffService _checkoutBffService;

        public ShoppingCartController(ICheckoutBffService checkoutBffService)
        {
            _checkoutBffService = checkoutBffService;
        }

        [Route("")]
        public async Task<IActionResult> Index()
        {
            return View(await _checkoutBffService.GetShoppingCart());
        }

        [HttpPost]
        [Route("add-item")]
        public async Task<IActionResult> AddItem(ShoppingCartItemViewModel shoppingCartItem)
        {
            var resposta = await _checkoutBffService.AddShoppingCartItem(shoppingCartItem);

            if (ResponseHasErrors(resposta)) return View("Index", await _checkoutBffService.GetShoppingCart());

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Route("update-item")]
        public async Task<IActionResult> UpdateItem(Guid productId, int quantity)
        {
            var item = new ShoppingCartItemViewModel { ProductId = productId, Quantity = quantity };
            var resposta = await _checkoutBffService.UpdateShoppingCartItem(productId, item);

            if (ResponseHasErrors(resposta)) return View("Index", await _checkoutBffService.GetShoppingCart());

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Route("remove-item")]
        public async Task<IActionResult> RemoveItem(Guid productId)
        {
            var resposta = await _checkoutBffService.RemoveItemFromShoppingCart(productId);

            if (ResponseHasErrors(resposta)) return View("Index", await _checkoutBffService.GetShoppingCart());

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Route("apply-voucher")]
        public async Task<IActionResult> ApplyVoucher(string voucherCode)
        {
            var resposta = await _checkoutBffService.ApplyVoucher(voucherCode);

            if (ResponseHasErrors(resposta)) return View("Index", await _checkoutBffService.GetShoppingCart());

            return RedirectToAction("Index");
        }
    }
}

src/web/DevStore.WebApp.MVC/Extensions/PagingViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using DevStore.WebApp.MVC.Models;

namespace DevStore.WebApp.MVC.Extensions
{
    public class PagingViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(IPagedList pagingModel)
        {
            return View(pagingModel);
        }
    }
}

src/web/DevStore.WebApp.MVC/Views/Catalog/Index.cshtml
@using DevStore.WebApp.MVC.Extensions
@model PagedViewModel<ProductViewModel>

@{
    ViewData["Title"] = "Awesome products for developers, geeks and nerds :)";
}

<section>
    <div>
        <div style="background-image: url(images/banners/Template.jpg); height: 100%; background-position: center; background-repeat: no-repeat; background-size: cover">
            <div style="text-align: center;">
                <img src="~/images/banners/devstore.png" />
            </div>
        </div>
        <div class="container" style="padding-top: 20px">
            <div class="row">
                @{
                    if (Model.List.Any())
                    {
                        foreach (var produto in Model.List.Where(p => p.Active).OrderBy(p => p.Name))
                        {
                            <div class="col-md-3">
                                <div href="#" class="card card-product-grid">
                                    <a asp-controller="Catalog" asp-action="ProductDetails" asp-route-id="@produto.Id" class="img-wrap">
                                        <img src="~/images/catalog/@produto.Image" alt="@produto.Name">
                                    </a>
                                    <figcaption class="info-wrap">
                                        <a asp-controller="Catalog" asp-action="ProductDetails" asp-route-id="@produto.Id" class="title">
                                            <b> @produto.Name</b>
                                        </a>

                                        <small class="card-text">
                                            @this.StockMessage(produto.Stock)<br /><br />
                                            @produto.Description
                                        </small>
                                    </figcaption>
                                    <div class="card-footer price mt-1">
                                        <h3>@this.FormatMoney(produto.Price)</h3>
                                    </div>
                                </div>
                            </div>
                        }
                    }
                    else
                    {
                        <div class="col-md-12" style="text-align: center">
                            <h2>Oh no! 😮 <br><br> There's no products available. Try searching with another criteria</h2>
                        </div>                        
                    }                    
                }
            </div>

            <vc:paging paging-model="@Model"></vc:paging>

        </div>
    </div>
</section>

src/web/DevStore.WebApp.MVC/Views/Catalog/ProductDetails.cshtml
@using DevStore.WebApp.MVC.Extensions
@model DevStore.WebApp.MVC.Models.ProductViewModel
@{
    ViewData["Title"] = Model.Name;
}
<section class="section-content padding-y bg container">
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
                <article class="gallery-wrap">
                    <div class="img-big-wrap" style="text-align: center">
                        <img src="~/images/catalog/@Model.Image" alt="@Model.Name">
                    </div>
                </article>
            </aside>
            <main class="col-md-6 border-left">
                <article class="content-body">
                    <form asp-controller="ShoppingCart" asp-action="AddItem" method="post">
                        
                        <input type="hidden" id="ProductId" name="ProductId" value="@Model.Id" />

                        <h2 class="title">@Model.Name</h2>

                        <div class="rating-wrap my-3">
                            <ul class="rating-stars">
                                <li style="width: 80%" class="stars-active">
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </li>
                                <li>
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </li>
                            </ul>
                            <small class="label-rating text-muted">132 ratings</small>
                            <small class="label-rating text-success"> <i class="fa fa-clipboard-check"></i> 154 units solds</small>
                        </div>

                        <div class="mb-3">
                            <var class="price h4">@this.FormatMoney(Model.Price)</var>
                        </div>

                        <h5>@Model.Description</h5><br/>
                        <p> @this.StockMessage(Model.Stock)</p>

                        <hr>

                        @{
                            if (Model.Stock > 0)
                            {
                                <div class="form-row">
                                    <div class="form-group col-md flex-grow-0">
                                        <label>Quantity</label>
                                        <div class="input-group input-spinner">
                                            <select id="Quantidade" name="Quantity" class="form-control">
                                                <option value="1">1</option>
                                                <option value="2">2</option>
                                                <option value="3">3</option>
                                                <option value="4">4</option>
                                                <option value="5">5</option>
                                            </select>
                                        </div>
                                    </div>

                                </div>
                                <br/>
                                <button type="submit" class="btn  btn-outline-primary">
                                    <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"> &nbsp;</i>
                                </button>

                            }
                        }

                        <a asp-action="Index" class="btn  btn-info">
                            <span class="text">Back</span>
                        </a>
                    </form>
                </article>
            </main>
        </div>
    </div>
</section>