src/web/DevStore.WebApp.MVC/Models/OrderViewModel.cs
using System;
using System.Collections.Generic;

namespace DevStore.WebApp.MVC.Models
{
    public class OrderViewModel
    {
        #region Order
        public int Code { get; set; }

        // Authorized = 1,
        // Paid = 2,
        // Refused = 3,
        // Chargeback = 4,
        // Canceled = 5
        public int Status { get; set; }
        public DateTime Date { get; set; }
        public decimal Amount { get; set; }

        public decimal Discount { get; set; }
        public bool HasVoucher { get; set; }

        public List<OrderItemViewModel> OrderItems { get; set; } = new List<OrderItemViewModel>();

        #endregion

        #region Order Item

        public class OrderItemViewModel
        {
            public Guid OrderId { get; set; }
            public string Name { get; set; }
            public int Quantity { get; set; }
            public decimal Price { get; set; }
            public string Image { get; set; }
        }

        #endregion

        #region Address

        public AddressViewModel Address { get; set; }

        #endregion
    }
}

src/web/DevStore.WebApp.MVC/Controllers/CatalogController.cs
using DevStore.WebApp.MVC.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace DevStore.WebApp.MVC.Controllers
{
    public class CatalogController : MainController
    {
        private readonly ICatalogService _catalogService;

        public CatalogController(ICatalogService catalogService)
        {
            _catalogService = catalogService;
        }

        [HttpGet]
        [Route("")]
        [Route("showcase")]
        public async Task<IActionResult> Index([FromQuery] int ps = 8, [FromQuery] int page = 1, [FromQuery] string q = null)
        {
            var products = await _catalogService.ListAll(ps, page, q);
            ViewBag.Search = q;
            products.ReferenceAction = "Index";

            return View(products);
        }

        [HttpGet]
        [Route("products/{id}")]
        public async Task<IActionResult> ProductDetails(Guid id)
        {
            var product = await _catalogService.GetById(id);

            return View(product);
        }
    }
}

src/web/DevStore.WebApp.MVC/Controllers/CustomerController.cs
using DevStore.WebApp.MVC.Models;
using DevStore.WebApp.MVC.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace DevStore.WebApp.MVC.Controllers
{
    [Authorize]
    public class CustomerController : MainController
    {
        private readonly ICustomerService _customerService;

        public CustomerController(ICustomerService customerService)
        {
            _customerService = customerService;
        }

        [HttpPost]
        public async Task<IActionResult> NewAddress(AddressViewModel address)
        {
            var response = await _customerService.AddAddress(address);

            if (ResponseHasErrors(response)) TempData["Errors"] =
                ModelState.Values.SelectMany(v => v.Errors.Select(e => e.ErrorMessage)).ToList();

            return RedirectToAction("DeliveryAddress", "Order");
        }
    }
}

src/web/DevStore.WebApp.MVC/Controllers/OrderController.cs
using DevStore.WebApp.MVC.Models;
using DevStore.WebApp.MVC.Services;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace DevStore.WebApp.MVC.Controllers
{
    public class OrderController : MainController
    {
        private readonly ICustomerService _customerService;
        private readonly ICheckoutBffService _checkoutBffService;

        public OrderController(ICustomerService customerService,
            ICheckoutBffService checkoutBffService)
        {
            _customerService = customerService;
            _checkoutBffService = checkoutBffService;
        }

        [HttpGet]
        [Route("delivery-address")]
        public async Task<IActionResult> DeliveryAddress()
        {
            var shoppingCart = await _checkoutBffService.GetShoppingCart();
            if (shoppingCart.Items.Count == 0) return RedirectToAction("Index", "ShoppingCart");

            var endereco = await _customerService.GetAddress();
            var order = _checkoutBffService.MapToOrder(shoppingCart, endereco);

            return View(order);
        }

        [HttpGet]
        [Route("payment")]
        public async Task<IActionResult> Payment()
        {
            var shoppingCart = await _checkoutBffService.GetShoppingCart();
            if (shoppingCart.Items.Count == 0) return RedirectToAction("Index", "ShoppingCart");

            var order = _checkoutBffService.MapToOrder(shoppingCart, null);

            return View(order);
        }

        [HttpPost]
        [Route("finish-order")]
        public async Task<IActionResult> FinishOrder(TransactionViewModel transaction)
        {
            if (!ModelState.IsValid) return View("Payment", _checkoutBffService.MapToOrder(await _checkoutBffService.GetShoppingCart(), null));

            var retorno = await _checkoutBffService.FinishOrder(transaction);

            if (ResponseHasErrors(retorno))
            {
                var shoppingCart = await _checkoutBffService.GetShoppingCart();
                if (shoppingCart.Items.Count == 0) return RedirectToAction("Index", "ShoppingCart");

                var orderMap = _checkoutBffService.MapToOrder(shoppingCart, null);
                return View("Payment", orderMap);
            }

            return RedirectToAction("OrderDone");
        }

        [HttpGet]
        [Route("order-done")]
        public async Task<IActionResult> OrderDone()
        {
            return View("OrderDone", await _checkoutBffService.GetLastOrder());
        }

        [HttpGet("my-orders")]
        public async Task<IActionResult> MyOrders()
        {
            var model = await _checkoutBffService.GetCustomersById();
            return View(model);
        }
    }
}

src/web/DevStore.WebApp.MVC/Views/Order/DeliveryAddress.cshtml
@using DevStore.WebApp.MVC.Extensions
@model DevStore.WebApp.MVC.Models.TransactionViewModel

@{
    ViewData["Title"] = "Confirm your order";
}

<section class="padding-y">
    <div class="container">

        <vc:Summary></vc:Summary>

        @if (Model.Items.Any())
        {
            <div class="card">
                <div class="tracking-wrap">
                    <div class="step active">
                        <span class="icon">
                            <i class="fa fa-location-arrow"></i>
                        </span>
                        <span class="text"> Address</span>
                    </div>
                    <div class="step">
                        <span class="icon">
                            <i class="fa fa-credit-card"></i>
                        </span>
                        <span class="text"> Payment </span>
                    </div>
                    <div class="step">
                        <span class="icon">
                            <i class="fa fa-check-square"></i>
                        </span>
                        <span class="text"> Confirm</span>
                    </div>
                </div>
                <article class="card-body">
                    <header class="mb-4">
                        <h4 class="card-title">Your Order</h4>
                    </header>
                    <div class="row">
                        @foreach (var item in Model.Items)
                        {
                            <div class="col-md-6">
                                <figure class="itemside  mb-3">
                                    <div class="aside">
                                        <img src="~/images/catalog/@item.Image" alt="@item.Name" class="border img-xs">
                                    </div>
                                    <figcaption class="info">
                                        <p>
                                            <b>@item.Name</b>
                                        </p>
                                        <span>@this.UnitByProductAmount(item.Quantity, item.Price) </span>
                                    </figcaption>
                                </figure>
                            </div>
                        }
                    </div>
                </article>

                <partial name="_FinanceSummary" model="Model" />

                <div class="card-body border-top">
                    <partial name="_Address" model="Model" />
                </div>
                <div class="card-body border-top">
                    @if (Model.Address != null)
                    {
                        <div class="text-left">
                            <a asp-controller="Order" asp-action="Payment" class="btn btn-primary float-md-right"> Payment <i class="fa fa-chevron-right"></i> </a>
                        </div>
                    }
                    <a asp-controller="ShoppingCart" asp-action="Index" class="btn btn-light"> <i class="fa fa-chevron-left"></i> Go back to Shopping Cart </a>
                </div>
            </div>
        }
    </div>
</section>

<partial name="_NewAddress" />

@section Scripts {

    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(document).ready(function () {
            BuscaCep();
        });
    </script>

}

src/web/DevStore.WebApp.MVC/Views/Order/MyOrders.cshtml
@using DevStore.WebApp.MVC.Extensions
@model IEnumerable<DevStore.WebApp.MVC.Models.OrderViewModel>

@{
    ViewData["Title"] = "My Orders";
}

<section class="padding-y">
    <div class="container">

        @{
            if (Model.Any())
            {

                foreach (var order in Model.OrderBy(p => p.Date))
                {
                    <div class="col-md-12" style="padding-bottom: 35px">
                        <article class="card">
                            <header class="card-header">
                                <b class="d-inline-block mr-3">Order ID: #@order.Code @Html.Raw(this.ShowStatus(order.Status))</b>
                                <span>@order.Date.ToLongDateString()</span>
                            </header>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-4">
                                        <h6 class="text-muted">Payment</h6>
                                        <span class="text-success">
                                            <i class="fas fa-credit-card"></i>
                                            Made by Credit Card
                                        </span>

                                        <p style="margin-top: 20px">
                                            <span class="b">Amount: @this.FormatMoney(order.Amount)</span>
                                        </p>

                                    </div>
                                    <div class="col-md-8">
                                        <h6 class="text-muted">Delivery Address</h6>
                                        <p>
                                            @order.Address.ToString()
                                        </p>
                                    </div>
                                </div>
                                <hr>
                                <ul class="row">
                                    @{
                                        foreach (var item in order.OrderItems)
                                        {
                                            <li class="col-md-4">
                                                <figure class="itemside  mb-3">
                                                    <div class="aside">
                                                        <img src="~/images/catalog/@item.Image" alt="@item.Name" class="border img-xs">
                                                    </div>
                                                    <figcaption class="info">
                                                        <p>
                                                            <b>@item.Name</b>
                                                        </p>
                                                        <span>@this.UnitByProductAmount(item.Quantity, item.Price) </span>
                                                    </figcaption>
                                                </figure>
                                            </li>

                                        }
                                    }
                                </ul>
                            </div>
                        </article>
                    </div>
                }
            }
            else
            {
                <div class="col-md-12" style="padding-bottom: 35px">
                    <article class="card">
                        <header class="card-header">
                            <b class="d-inline-block mr-3">You don't have any orders! Shop with us!</b>
                        </header>
                        <div class="card-body">
                            <div class="row">
                                <a asp-controller="Catalog" asp-action="Index">Go shopping!</a>
                            </div>
                        </div>
                    </article>
                </div>
            }
        }
    </div>
</section>

src/web/DevStore.WebApp.MVC/Views/Order/OrderDone.cshtml
@using DevStore.WebApp.MVC.Extensions
@model DevStore.WebApp.MVC.Models.OrderViewModel

@{
    ViewData["Title"] = "Order done!";
}

<section class="padding-y">
    <div class="container">

        <vc:Summary></vc:Summary>

        @{
            if (Model.OrderItems.Any())
            {
                <div class="card">
                    <div class="tracking-wrap">
                        <div class="step active">
                            <span class="icon">
                                <i class="fa fa-location-arrow"></i>
                            </span>
                            <span class="text"> Address</span>
                        </div>
                        <div class="step active">
                            <span class="icon">
                                <i class="fa fa-credit-card"></i>
                            </span>
                            <span class="text"> Payment </span>
                        </div>
                        <div class="step active">
                            <span class="icon">
                                <i class="fa fa-check-square"></i>
                            </span>
                            <span class="text"> Confirm</span>
                        </div>
                    </div>
                    <article class="card-body">
                        <header class="mb-4">
                            <h4 class="card-title">Success at your Order!</h4>
                        </header>
                        <div class="row">
                            @{
                                foreach (var item in Model.OrderItems)
                                {
                                    <div class="col-md-6">
                                        <figure class="itemside  mb-3">
                                            <div class="aside">
                                                <img src="~/images/catalog/@item.Image" alt="@item.Name" class="border img-xs">
                                            </div>
                                            <figcaption class="info">
                                                <p>
                                                    <b>@item.Name</b>
                                                </p>
                                                <span>@this.UnitByProductAmount(item.Quantity, item.Price) </span>
                                            </figcaption>
                                        </figure>
                                    </div>
                                }
                            }

                        </div>
                    </article>

                    <header class="card-header">
                        <h3 class="d-inline-block mr-3">Order number: #@Model.Code</h3>
                    </header>
                    <article class="card-body border-top">

                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-8">
                                    <h6 class="text-muted">Delivery </h6>
                                    <p>
                                        @Model.Address.ToString()
                                    </p>
                                </div>
                                <div class="col-md-4">
                                    <h6 class="text-muted">Payment</h6>
                                    <span class="text-success">
                                        <i class="fas fa-credit-card"></i>
                                        Transaction by credit card
                                    </span>
                                    <p>
                                        <span class="b">Amount:  @this.FormatMoney(Model.Amount)</span>
                                    </p>
                                </div>
                            </div>

                        </div>
                    </article>

                    <div class="card-body border-top">
                        <div class="text-left">
                            <a asp-controller="Order" asp-action="MyOrders" class="btn btn-primary float-md-right"> My Orders <i class="fa fa-chevron-right"></i> </a>
                        </div>
                    </div>

                </div>
            }
        }
    </div>
</section>

@section Scripts {

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

}

src/web/DevStore.WebApp.MVC/Views/Order/_Address.cshtml
@model DevStore.WebApp.MVC.Models.TransactionViewModel


<h4 class="card-title">Address</h4>
@{
    if (Model.Address == null)
    {
        <div class="text-left">
            <a href="javascript:void(0)" class="btn btn-primary float-md-left" data-toggle="modal" data-target="#addressModal"> <i class="fa fa-location-arrow"></i> Add Address</a>
        </div>
    }
    else
    {
        <div class="row">
            <div class="col-9 text-left">
                @Model.Address.ToString()
            </div>
            <div class="col-3 text-right">
                <a href="javascript:void(0)" class="btn btn-primary float-md-right"> <i class="fa fa-location-arrow"></i> Update Address</a>
            </div>
        </div>
    }
}



src/web/DevStore.WebApp.MVC/Views/Order/_FinanceSummary.cshtml
@using DevStore.WebApp.MVC.Extensions
@model DevStore.WebApp.MVC.Models.TransactionViewModel

<article class="card-body border-top">
    <dl class="row">
        @if (Model.HasVoucher)
        {
            <dt class="col-sm-10">Amount: <span class="float-right text-muted">@Model.Items.Sum(i => i.Quantity) items</span></dt>
            <dd class="col-sm-2 text-right">
                <strong>@this.FormatMoney(Model.Amount + Model.Discount)</strong>
            </dd>

            <dt class="col-sm-10">Discount: <span class="float-right text-muted">@Model.Voucher</span></dt>
            <dd class="col-sm-2 text-danger text-right">
                <strong>@this.FormatMoney(Model.Discount)</strong>
            </dd>
        }
        <dt class="col-sm-10">Total:</dt>
        <dd class="col-sm-2 text-right">
            <strong class="h5 text-dark">@this.FormatMoney(Model.Amount)</strong>
        </dd>
    </dl>
</article>

src/web/DevStore.WebApp.MVC/Views/Order/_NewAddress.cshtml
@model DevStore.WebApp.MVC.Models.TransactionViewModel
@{
    ViewData["Title"] = "New Address";
}

<div class="modal fade" id="addressModal" tabindex="-1" role="dialog" aria-labelledby="addressModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id="myModalContent">

                <div class="modal-header">
                    <h4 class="modal-title">@ViewData["Title"]</h4>
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">×</span><span class="sr-only">Close</span>
                    </button>
                </div>

                <form asp-action="NewAddress" asp-controller="Customer">
                    <div class="modal-body">

                        <div class="form-group">
                            <label asp-for="Address.ZipCode"></label>
                            <input asp-for="Address.ZipCode" class="form-control" />
                            <span asp-validation-for="Address.ZipCode" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Address.StreetAddress"></label>
                            <input asp-for="Address.StreetAddress" class="form-control" />
                            <span asp-validation-for="Address.StreetAddress" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Address.BuildingNumber"></label>
                            <input asp-for="Address.BuildingNumber" class="form-control" />
                            <span asp-validation-for="Address.BuildingNumber" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Address.SecondaryAddress"></label>
                            <input asp-for="Address.SecondaryAddress" class="form-control" />
                            <span asp-validation-for="Address.SecondaryAddress" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Address.Neighborhood"></label>
                            <input asp-for="Address.Neighborhood" class="form-control" />
                            <span asp-validation-for="Address.Neighborhood" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Address.City"></label>
                            <input asp-for="Address.City" class="form-control" />
                            <span asp-validation-for="Address.City" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Address.State"></label>
                            <input asp-for="Address.State" class="form-control" />
                            <span asp-validation-for="Address.State" class="text-danger"></span>
                        </div>

                        <div class="modal-footer">
                            <div>
                                <input type="submit" value="Add Address" class="btn btn-success" />
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>